<a href="https://colab.research.google.com/github/9159647312/E-Commerce-sales-performance-analysis/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:


import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

#addition
c = a+b
print(c)

#multiplication
d= a*b
print(d)

#power
e = a**2
print(e)

#sqrt
f = np.sqrt(a)
print(f)

#sum
g = np.sum(a)
print(g)




[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
6


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5]) #1D arr
print(arr)

[1 2 3 4 5]


In [4]:


#error hanling

try:
  n = int(input("Enter a number:"))
  print(n)

except:
  print("Invalid input")

Enter a number:ak
Invalid input


In [5]:
#practice: Attendence Calculator

def percentage(x,y):
  perc = (y/x)*100
  return round(perc,2 )

def status(percentage):
  if percentage >= 75:
    return "Eligible"
  else:
    return "Not eligible"

try:
  x = int(input("Total classes:"))
  y = int(input("classes attented:"))

  pct = percentage(x,y)
  st = status(pct)

  print("Percentage:",pct,"%")
  print("Status:",st)

except:
  print("Invalid input")



Total classes:11
classes attented:5
Percentage: 45.45 %
Status: Not eligible


In [6]:
import numpy as np
arr = np.array([[1,2],[2,4]]) #2D arr
print(arr)

[[1 2]
 [2 4]]


In [7]:
import numpy as np
arr = np.array([[[1,2],[2,4]],[[3,5],[6,7]]]) #3D arr
print(arr)

[[[1 2]
  [2 4]]

 [[3 5]
  [6 7]]]


In [9]:
# zeros()

import numpy as np
arr = np.zeros([2,3])
print(arr)



[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# ones()

import numpy as np
arr = np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#arange()

import numpy as np
arr = np.arange(1,10)
print(arr)


arr2 = np.arange(1,10,2)
print(arr2)


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [12]:
# linspace() --> evenly spaced value

import numpy as np
arr = np.linspace(0,10,5)
print(arr)




[ 0.   2.5  5.   7.5 10. ]


In [13]:

#random.rand()

import numpy as np
arr = np.random.rand(3)
res = np.round(arr,2)
print(res)

[0.3  0.76 0.85]


In [14]:


#eye()  --> Identity Matrix

import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
