<a href="https://colab.research.google.com/github/9159647312/E-Commerce-sales-performance-analysis/blob/main/day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:

#median() --> middle value when sorted

import numpy as np

a = np.array([6,2,1,6,3,9])
median = np.median(a)
print(median)

4.5


In [1]:
#Indexing & Slicing

import numpy as np
marks = np.array([90,80,75,60,100])
print(marks[1:4])

[80 75 60]


In [11]:

#practice1

import numpy as np
scores = np.array([78,85,92,67,88])
total = np.sum(scores)
avg = np.mean(scores)
maximumscore = np.max(scores)
minimumscore = np.min(scores)

print(total)
print(avg)
print(maximumscore)
print(minimumscore)

410
82.0
92
67


In [5]:

#practice2

sales = np.array([12000,15000,18000,14000,20000])
total_sales = np.sum(sales)
avg = np.mean(sales)
max = np.max(sales)
min = np.min(sales)

print(total_sales)
print(avg)
print(max)
print(min)

79000
15800.0
20000
12000


In [12]:

#Reshape & Transpose

import numpy as np

a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)

print(b)

c= b.transpose()
print("\n",c)

[[1 2 3]
 [4 5 6]]

 [[1 4]
 [2 5]
 [3 6]]


In [14]:



#Aggregation & Axis Operation

#sum() --> total

import numpy as np

a = np.array([1,2,3,4,5,6])
total = np.sum(a)
print(total)


21


In [15]:


#mean --> average

import numpy as np

a = np.array([6,2,1,6,3,9])
avg = np.mean(a)
print(avg)

4.5
